version: '3.8'

services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=llm_vectors
      - POSTGRES_USER=llm_user
      - POSTGRES_PASSWORD=11m_s3cr3t
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080
networks:
  default:
    name: llm-chat-network

